import { PartResult } from "./types.js";

export const mockParts: PartResult[] = [
  {
    manufacturer: "Yageo",
    manufacturerPartNumber: "RC0603FR-0710KL",
    digiKeyPartNumber: "311-10.0KHRCT-ND",
    description: "RES SMD 10K OHM 1% 1/10W 0603",
    stock: 125000,
    unitPrice: 0.012,
    url: "https://www.digikey.com/en/products/detail/yageo/RC0603FR-0710KL/727385",
    attributes: {
      category: "resistor",
      value: "10 kOhms",
      tolerance: "±1%",
      power: "0.1W",
      package: "0603 (1608 Metric)",
      material: "Thick Film",
    },
  },
  {
    manufacturer: "Murata Electronics",
    manufacturerPartNumber: "GRM188R60J106ME47D",
    description: "CAP CER 10UF 6.3V X5R 0603",
    stock: 54000,
    unitPrice: 0.045,
    url: "https://www.digikey.com/en/products/detail/murata-electronics/GRM188R60J106ME47D/4905340",
    attributes: {
      category: "capacitor",
      value: "10 uF",
      voltage: "6.3V",
      dielectric: "X5R",
      package: "0603",
    },
  },
  {
    manufacturer: "Texas Instruments",
    manufacturerPartNumber: "OPA333AIDBVR",
    description: "OP-AMP ZERO-DRIFT CMOS RRO SOT23-5",
    stock: 18000,
    unitPrice: 0.62,
    url: "https://www.digikey.com/en/products/detail/texas-instruments/OPA333AIDBVR/935222",
    attributes: {
      category: "amplifier",
      type: "op-amp",
      supplyVoltage: "1.8V to 5.5V",
      package: "SOT-23-5",
      offset: "10 uV",
    },
  },
  {
    manufacturer: "Amphenol ICC",
    manufacturerPartNumber: "10118193-0001LF",
    description: "CONN MICRO USB B RECPT R/A SMD",
    stock: 7200,
    unitPrice: 0.38,
    url: "https://www.digikey.com/en/products/detail/amphenol-icc-fci/10118193-0001LF/2785378",
    attributes: {
      category: "connector",
      interface: "Micro USB B",
      mount: "SMT",
      orientation: "Right Angle",
    },
  },
];
