import "dotenv/config";
import OpenAI from "openai";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { execFile } from "child_process";
import { promisify } from "util";
import os from "os";

const execFileAsync = promisify(execFile);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPO_ROOT = path.join(__dirname, "..");
const RUN_BASE = path.join(REPO_ROOT, "pipeline", "parallel_runs");
const resolvedModel = process.env.OPENAI_MODEL || "gpt-4o-mini";
const DEFAULT_MODEL = resolvedModel;
const CONCEPT_MODEL = process.env.OPENAI_MODEL_CONCEPT || DEFAULT_MODEL;
const MAX_CONCEPTS = 3;
const SYSIDE_VENV = process.env.SYSIDE_VENV || path.join(REPO_ROOT, ".venv");
const SYSIDE_PY = path.join(SYSIDE_VENV, "bin", "python");

type Status = "queued" | "running" | "success" | "error";

interface StageState {
  status: Status;
  message?: string;
  detail?: string;
  startedAt?: string;
  endedAt?: string;
}

interface ConceptSpec {
  name: string;
  approach: string;
  highlights?: string[];
}

interface ConceptStage extends StageState {
  index: number;
  concept?: ConceptSpec;
  sysmlPath?: string;
  sysml?: string;
}

interface RunState {
  id: string;
  nl: string;
  createdAt: string;
  status: "running" | "done" | "error";
  runDir: string;
  log: string[];
  outputs: {
    requirementsSysml?: string;
    requirementsPath?: string;
    concepts?: ConceptSpec[];
    conceptSysml?: ConceptStage[];
  };
  stages: {
    requirements: StageState;
    concepts: StageState;
    conceptsExpansion: ConceptStage[];
  };
}

type Subscriber = (state: RunState) => void;

const runs = new Map<string, RunState>();
const subscribers = new Map<string, Set<Subscriber>>();

const client = new OpenAI();

const nowISO = () => new Date().toISOString();

const ensureDir = (p: string) => fs.mkdirSync(p, { recursive: true });

const writeJson = (p: string, data: unknown) => {
  fs.writeFileSync(p, JSON.stringify(data, null, 2), "utf-8");
};

// No hard-coded SysML fallbacks; all SysML is generated by the LLM.

const appendLog = (p: string, entry: Record<string, unknown>) => {
  fs.appendFileSync(p, `${JSON.stringify({ ts: nowISO(), ...entry })}\n`, "utf-8");
};

const broadcast = (runId: string) => {
  const state = runs.get(runId);
  if (!state) return;
  // persist snapshot
  try {
    writeJson(path.join(state.runDir, "state.json"), state);
  } catch {
    /* ignore persistence errors */
  }
  const listeners = subscribers.get(runId);
  if (!listeners) return;
  for (const fn of listeners) {
    try {
      fn(state);
    } catch {
      /* ignore listener errors */
    }
  }
};

export const subscribeSimpleRun = (runId: string, fn: Subscriber) => {
  const set = subscribers.get(runId) ?? new Set<Subscriber>();
  set.add(fn);
  subscribers.set(runId, set);
  return () => {
    const current = subscribers.get(runId);
    if (!current) return;
    current.delete(fn);
    if (current.size === 0) {
      subscribers.delete(runId);
    }
  };
};

const loadRunStateFromDisk = (runId: string): RunState | undefined => {
  try {
    const dir = path.join(RUN_BASE, runId);
    const statePath = path.join(dir, "state.json");
    if (!fs.existsSync(statePath)) return undefined;
    const raw = fs.readFileSync(statePath, "utf-8");
    return JSON.parse(raw) as RunState;
  } catch {
    return undefined;
  }
};

export const getSimpleRunState = (runId: string) => {
  const inMemory = runs.get(runId);
  if (inMemory) return inMemory;
  return loadRunStateFromDisk(runId);
};

const randomId = () => {
  const ts = new Date().toISOString().replace(/[-:T.Z]/g, "").slice(0, 14);
  const suffix = Math.random().toString(36).slice(2, 6);
  return `${ts}_${suffix}`;
};

const choosePython = () => {
  if (fs.existsSync(SYSIDE_PY)) return SYSIDE_PY;
  return "python";
};

const runTranslationCheck = async (nlPath: string, sysmlPath: string) => {
  const script = path.join(REPO_ROOT, "pipeline", "translation_checker.py");
  try {
    const { stdout } = await execFileAsync(choosePython(), [script, "--nl-file", nlPath, "--sysml-file", sysmlPath], {
      cwd: REPO_ROOT,
      env: { ...process.env },
      timeout: 120000,
    });
    const parsed = JSON.parse(stdout);
    const missing = parsed?.missing_requirements ?? [];
    const partial = parsed?.partial_or_weakened ?? [];
    const extraneous = parsed?.extraneous_sysml ?? [];
    const ok = (!missing || missing.length === 0) && (!partial || partial.length === 0);
    return { ok, report: parsed, missing, partial, extraneous };
  } catch (error) {
    return { ok: false, report: { error: (error as Error).message }, missing: [], partial: [], extraneous: [] };
  }
};

const sysideCheck = async (sysmlPath: string) => {
  const python = choosePython();
  const args = ["-m", "syside", "check", path.basename(sysmlPath)];
  try {
    const { stdout, stderr } = await execFileAsync(python, args, {
      cwd: path.dirname(sysmlPath),
      timeout: 60000,
      maxBuffer: 2 * 1024 * 1024,
    });
    const success = stdout.includes("Checks passed!");
    return { success, stdout: stdout.trim(), stderr: stderr.trim() };
  } catch (err) {
    const e = err as Error & { stdout?: string; stderr?: string };
    return {
      success: false,
      stdout: (e.stdout || "").toString(),
      stderr: (e.stderr || e.message || "").toString(),
    };
  }
};

type ChatMessage = { role: "system" | "user" | "assistant"; content: string };

const callChat = async (
  messages: ChatMessage[],
  model = DEFAULT_MODEL,
  _temperature: number | undefined = undefined,
  debugPath?: string,
): Promise<string> => {
  const doCall = async (msgs: ChatMessage[]) => {
    const completion = await client.responses.create({
      model,
      input: msgs,
      max_output_tokens: 4000,
      reasoning: { effort: "low" },
    });
    if (debugPath) {
      const payload = {
        requestMessages: msgs,
        completion,
      };
      try {
        fs.writeFileSync(debugPath, JSON.stringify(payload, null, 2), "utf-8");
      } catch {
        /* ignore debug write errors */
      }
    }
    const outputText = (completion as any).output_text;
    if (typeof outputText === "string" && outputText.trim()) return outputText.trim();
    // fallback: stitch text from output array
    const pieces: string[] = [];
    for (const item of (completion as any).output ?? []) {
      for (const c of item.content ?? []) {
        if (typeof c.text === "string") pieces.push(c.text);
      }
    }
    return pieces.join("").trim();
  };

  let text = await doCall(messages);
  if (!text || !text.trim()) {
    // fallback: minimal prompt to coerce output
    const fallback: ChatMessage[] = [
      { role: "system", content: "Return ONLY SysMLv2 code. No prose." },
      { role: "user", content: messages.map((m) => `${m.role}: ${m.content}`).join("\n\n") },
    ];
    text = await doCall(fallback);
  }
  return text.trim();
};

const buildRequirementsMessages = (nl: string, previous?: string, feedback?: string): ChatMessage[] => {
  const messages: ChatMessage[] = [
    {
      role: "system",
      content:
        "You are the Requirements Agent. Convert the natural-language brief into a fully decomposed, design-agnostic SysMLv2 requirements package with explicit quantitative or boolean constraints.\n" +
        "- Use package RequirementsOnly with public import ScalarValues::*.\n" +
        "- Extract only what is stated or clearly implied in the NL brief; do not add new feature categories.\n" +
        "- Emit 8–15 requirement defs (RQ_001..). Each requirement body must contain exactly one line: text = \"...\"; (semicolon required; single line only).\n" +
        "- Emit a matching constraint def for each requirement (C_001..) that operationalizes the same requirement using numeric bounds, enums/strings, or booleans drawn from the NL (use reasonable placeholders only when needed and keep them minimal). Each 'in' line ends with a semicolon; the boolean expression has no trailing semicolon.\n" +
        "- Keep constraints simple (<=, >=, =, and/or). Avoid ternaries and compound arithmetic; avoid 'whichever is greater' forms.\n" +
        "- Do not include comments or prose. ASCII only. Close every numeric literal (use 95.0 not 95.).\n" +
        "- Keep total output under 180 lines and return only the SysML package.",
    },
    {
      role: "user",
      content: `Natural-language brief:\n${nl}\n\nTemplate (match style):\npackage RequirementsOnly {\n  public import ScalarValues::*;\n  requirement def RQ_001 {\n    text = \"...\";\n  }\n  constraint def C_001 {\n    in x: Real;\n    (x >= 0.0) and (x <= 1.0)\n  }\n}\n\nRules to obey: semicolon after every 'text =' and every 'in ...' line; no semicolon after the boolean expression; keep each text string on a single line with no embedded newlines; use plain ASCII quotes/dashes; fully close every expression.\n\nEmit only SysMLv2 code in this style.`,
    },
  ];
  if (previous) {
    messages.push({ role: "assistant", content: previous });
  }
  if (feedback) {
    messages.push({
      role: "system",
      content: `syside feedback:\n${feedback}\nFix issues and resend the entire model.`,
    });
  }
  return messages;
};

const buildConceptPrompt = (nl: string, requirementsSysml: string, concept: ConceptSpec): ChatMessage[] =>
  [
    {
      role: "system",
      content:
        "You are the Concept Realizer. Extend the provided requirements into a concrete concept-specific SysMLv2 design for this concept.\n" +
        "- Assume RequirementsOnly already exists; do not copy it. Create a package ConceptDesign that imports RequirementsOnly::* and ScalarValues::*.\n" +
        "- Define a main System part and add parts that make sense for this concept (e.g., actuation/launch, feed/handling, power, control, sensing, UI, safety, enclosure). Keep it structural with attributes.\n" +
        "- Use only part/attribute/constraint definitions; DO NOT use ports, flows, connections, bindings, inheritance, or instances.\n" +
        "- End every attribute line with a semicolon. Keep names meaningful to this concept (e.g., flywheelRPM, plungerPressure, camAngle_deg, magazineCapacity, batteryCapacity_mAh, controlMode).\n" +
        "- Add 3–6 constraint defs capturing key budgets or checks (runtime, energy, speed/force, safety interlocks). Each constraint: 'in' lines with semicolons, then a single simple comparison (<=, >=, =, and/or). No ternaries or complex arithmetic.\n" +
        "- No prose or comments. ASCII only. Keep it concise and syntactically valid SysMLv2.",
    },
    {
      role: "user",
      content: `Brief:\n${nl}\n\nRequirements (for context):\n${requirementsSysml}\n\nConcept to realize:\n${JSON.stringify(
        concept,
        null,
        2,
      )}\n\nEmit only SysMLv2 code for ConceptDesign. No commentary or markdown.`,
    },
  ];

const conceptGeneratorPrompt = (nl: string, requirementsSysml: string, count: number): ChatMessage[] =>
  [
    {
      role: "system",
      content:
        "You are the Concept Generator. Propose multiple *distinct* solution concepts that could satisfy the brief. " +
        "Each concept must follow this schema exactly: { \"name\": string, \"approach\": string (50-80 words, NL description of the architecture/operating principle), \"highlights\": string[3..6] of differentiating features }. " +
        "Ensure the concepts differ materially in actuation/structure/energy/storage/control philosophies (not just parameter tweaks). " +
        "Return only JSON: { \"concepts\": [ ... ] }. No prose or markdown outside the JSON.",
    },
    {
      role: "user",
      content: `Requirement:\n${nl}\n\nSysML snapshot for context:\n${requirementsSysml.slice(
        0,
        2500,
      )}\n\nGenerate at least ${count} diverse concepts (more is fine). JSON schema reminder: { \"concepts\": [ { \"name\": string, \"approach\": string, \"highlights\": string[] } ] }`,
    },
  ];

const parseConcepts = (raw: string, count: number): ConceptSpec[] => {
  try {
    const parsed = JSON.parse(raw);
    const data = Array.isArray(parsed) ? parsed : Array.isArray((parsed as any)?.concepts) ? (parsed as any).concepts : parsed;
    if (Array.isArray(data)) {
      return data
        .slice(0, count)
        .map((c, idx) => ({
          name: String(c?.name || `Concept ${idx + 1}`),
          approach: String(c?.approach || "").trim() || "No approach provided",
          highlights: Array.isArray(c?.highlights)
            ? c.highlights.map((h: unknown) => String(h))
            : undefined,
        }))
        .filter(Boolean);
    }
  } catch {
    /* fall through */
  }
  // fallback: three materially distinct generic architectures to avoid placeholders
  const fallback: ConceptSpec[] = [
    {
      name: "Dual-Flywheel Soft-Toss",
      approach:
        "Electric dual-flywheel launcher with variable wheel speed and adjustable chute angle. Gravity-fed ball stack with singulation gate; microcontroller sets RPM to control arc. Internal Li-ion pack powers motors and control; BLE used for drills and tempo selection.",
      highlights: ["dual flywheel", "adjustable chute angle", "BLE drill control", "gravity feed gate"],
    },
    {
      name: "Pneumatic Plunger Tosser",
      approach:
        "Low-pressure air cylinder drives a padded plunger to soft-toss balls along a short guide tube. Onboard compressor with small accumulator; solenoid valve meters shot energy. Rotary magazine indexes balls; Wi-Fi tablet interface sets pressure and cadence.",
      highlights: ["pneumatic plunger", "air accumulator", "rotary magazine", "Wi‑Fi control"],
    },
    {
      name: "Spring-Arm Cam Pitcher",
      approach:
        "Cam-driven spring arm flicks balls upward for soft toss. Brushless motor winds cam; mechanical clutch releases at set angle for repeatable trajectory. Hopper with escapement feeds one ball per cycle. LCD + buttons for cadence and angle presets.",
      highlights: ["cam + spring arm", "mechanical release", "hopper escapement", "local LCD controls"],
    },
  ];
  return fallback.slice(0, Math.max(count, 3));
};

const updateStage = (state: RunState, stageKey: keyof RunState["stages"], update: Partial<StageState>) => {
  const stage = state.stages[stageKey];
  Object.assign(stage, update);
};

const updateConceptStage = (state: RunState, idx: number, update: Partial<ConceptStage>) => {
  const stage = state.stages.conceptsExpansion[idx];
  Object.assign(stage, update);
};

const recordLog = (state: RunState, logPath: string, message: string) => {
  state.log.push(message);
  appendLog(logPath, { msg: message });
};

const generateRequirements = async (
  runId: string,
  nl: string,
  runDir: string,
  state: RunState,
  logPath: string,
  maxIters = 30,
) => {
  const reqDir = path.join(runDir, "requirements");
  ensureDir(reqDir);
  updateStage(state, "requirements", { status: "running", startedAt: nowISO(), message: "Generating requirements SysML" });
  broadcast(runId);

  let feedback: string | undefined;
  let previous: string | undefined;
  let finalSysml = "";
  let finalPath = "";

  for (let i = 0; i < maxIters; i++) {
    const attempt = i + 1;
    recordLog(state, logPath, `requirements: attempt ${attempt}`);
    const messages = buildRequirementsMessages(nl, previous, feedback);
    let sysml = "";
    try {
      const debugPath = path.join(reqDir, `iteration_${attempt.toString().padStart(2, "0")}_raw.json`);
      sysml = await callChat(messages, DEFAULT_MODEL, undefined, debugPath);
    } catch (err) {
      appendLog(logPath, { stage: "requirements", attempt, error: (err as Error).message });
      feedback = "Model call failed; regenerate with full requirements decomposition.";
      continue;
    }
    if (!sysml || !sysml.trim()) {
      feedback = "Empty response from model, regenerate with full SysMLv2 requirements and constraints.";
      continue;
    }
    const attemptPath = path.join(reqDir, `iteration_${attempt.toString().padStart(2, "0")}.sysml`);
    fs.writeFileSync(attemptPath, sysml, "utf-8");
    previous = sysml;
    const check = await sysideCheck(attemptPath);
    appendLog(logPath, { stage: "requirements", attempt, success: check.success, stdout: check.stdout, stderr: check.stderr });
    const reqCount = (sysml.match(/\brequirement def\b/gi) || []).length;
    const requiresMoreDecomp = reqCount < 6;
    if (check.success) {
      if (requiresMoreDecomp && attempt < maxIters) {
        feedback =
          "Decompose further: include separate requirement defs for PM2.5, CO2, temperature, humidity, handheld form factor, rechargeable battery, runtime, Wi‑Fi, Bluetooth. Keep numeric/boolean attributes and paired constraints.";
        continue;
      }
      // translation checker pass?
      const nlPath = path.join(runDir, "prompt.txt");
      const tc = await runTranslationCheck(nlPath, attemptPath);
      appendLog(logPath, { stage: "requirements", attempt, translation_ok: tc.ok, translation_report: tc.report });
      if (!tc.ok && attempt < maxIters) {
        feedback = `Translation checker gaps:\nmissing: ${JSON.stringify(tc.missing)}\npartial: ${JSON.stringify(tc.partial)}`;
        continue;
      }
      if (tc.ok || attempt === maxIters) {
        finalSysml = sysml;
        finalPath = attemptPath;
        updateStage(state, "requirements", {
          status: tc.ok ? "success" : "error",
          detail: tc.ok ? "syside + translation check passed" : "translation checker still failing after maxIters",
          endedAt: nowISO(),
          message: tc.ok ? `requirements ok (iter ${attempt})` : "translation check failed",
        });
        if (tc.ok) {
          state.outputs.requirementsSysml = finalSysml;
          state.outputs.requirementsPath = finalPath;
          broadcast(runId);
          return { sysml: finalSysml, path: finalPath };
        }
      }
    }
    feedback = [check.stdout, check.stderr].filter(Boolean).join("\n").trim();
  }

  updateStage(state, "requirements", {
    status: "error",
    detail: "syside check did not pass",
    endedAt: nowISO(),
  });
  broadcast(runId);
  throw new Error("requirements stage failed");
};

const generateConcepts = async (
  runId: string,
  nl: string,
  requirementsSysml: string,
  state: RunState,
  runDir: string,
  logPath: string,
  count: number,
) => {
  updateStage(state, "concepts", { status: "running", startedAt: nowISO(), message: "Generating concepts" });
  broadcast(runId);
  recordLog(state, logPath, "concept generation started");
  const completion = await client.chat.completions.create({
    model: CONCEPT_MODEL,
    messages: conceptGeneratorPrompt(nl, requirementsSysml, count),
    response_format: { type: "json_object" },
    max_completion_tokens: 2000,
  });
  const raw = completion.choices[0]?.message?.content?.trim() || "";
  const concepts = parseConcepts(raw, count);
  state.outputs.concepts = concepts;
  fs.writeFileSync(path.join(runDir, "concepts.json"), JSON.stringify(concepts, null, 2), "utf-8");
  updateStage(state, "concepts", { status: "success", endedAt: nowISO(), message: `Generated ${concepts.length} concepts` });
  broadcast(runId);
  return concepts;
};

const generateConceptSysml = async (
  runId: string,
  nl: string,
  requirementsSysml: string,
  concept: ConceptSpec,
  idx: number,
  state: RunState,
  runDir: string,
  logPath: string,
  maxIters = 30,
) => {
  const stageIdx = idx;
  updateConceptStage(state, stageIdx, {
    status: "running",
    startedAt: nowISO(),
    message: `Concept ${idx + 1}: generating SysML`,
    concept,
  });
  broadcast(runId);
  recordLog(state, logPath, `concept_${idx + 1}: start`);

  const conceptDir = path.join(runDir, `concept_${idx + 1}`);
  ensureDir(conceptDir);
  let feedback: string | undefined;
  let previous: string | undefined;
  let finalSysml = "";
  let finalPath = "";

  for (let i = 0; i < maxIters; i++) {
    const attempt = i + 1;
    const messages = buildConceptPrompt(nl, requirementsSysml, concept);
    if (feedback) {
      messages.push({
        role: "system",
        content: `syside feedback:\n${feedback}\nRevise and resend ConceptDesign only.`,
      });
    }
    if (previous) {
      messages.push({ role: "assistant", content: previous });
    }
    let addition = await callChat(messages, DEFAULT_MODEL, undefined);
    if (!addition || !addition.trim()) {
      feedback = "Empty response; regenerate full ConceptDesign SysML.";
      continue;
    }
    const baseReq = requirementsSysml.trim();
    const combined = `${baseReq}\n\n${addition.trim()}\n`;
    const attemptPath = path.join(conceptDir, `iteration_${attempt.toString().padStart(2, "0")}.sysml`);
    fs.writeFileSync(attemptPath, combined, "utf-8");
    previous = addition;
    const check = await sysideCheck(attemptPath);
    appendLog(logPath, {
      stage: `concept_${idx + 1}`,
      attempt,
      success: check.success,
      stdout: check.stdout,
      stderr: check.stderr,
    });
    if (check.success) {
      finalSysml = combined;
      finalPath = attemptPath;
      updateConceptStage(state, stageIdx, {
        status: "success",
        sysml: finalSysml,
        sysmlPath: finalPath,
        endedAt: nowISO(),
        message: `Concept ${idx + 1} passed syside`,
      });
      if (!state.outputs.conceptSysml) state.outputs.conceptSysml = [];
      state.outputs.conceptSysml[stageIdx] = {
        ...state.stages.conceptsExpansion[stageIdx],
        sysml: finalSysml,
        sysmlPath: finalPath,
      };
      broadcast(runId);
      return { sysml: finalSysml, path: finalPath };
    }
    feedback = [check.stdout, check.stderr].filter(Boolean).join("\n").trim();
  }

  updateConceptStage(state, stageIdx, {
    status: "error",
    endedAt: nowISO(),
    message: `Concept ${idx + 1} did not pass syside`,
  });
  broadcast(runId);
  throw new Error(`concept ${idx + 1} failed`);
};

export const startSimpleRun = (nl: string, conceptCount = MAX_CONCEPTS) => {
  const runId = randomId();
  const runDir = path.join(RUN_BASE, runId);
  ensureDir(runDir);
  const logPath = path.join(runDir, "stage_log.jsonl");
  const state: RunState = {
    id: runId,
    nl,
    createdAt: nowISO(),
    status: "running",
    runDir,
    log: [],
    outputs: {},
    stages: {
      requirements: { status: "queued" },
      concepts: { status: "queued" },
      conceptsExpansion: Array.from({ length: conceptCount }).map((_, i) => ({
        status: "queued",
        index: i,
      })),
    },
  };
  runs.set(runId, state);
  broadcast(runId);

  // persist prompt
  fs.writeFileSync(path.join(runDir, "prompt.txt"), nl, "utf-8");

  (async () => {
    try {
      const req = await generateRequirements(runId, nl, runDir, state, logPath);
      const concepts = await generateConcepts(
        runId,
        nl,
        req.sysml,
        state,
        runDir,
        logPath,
        Math.min(conceptCount, MAX_CONCEPTS),
      );
      const promises = concepts.map((concept, idx) =>
        generateConceptSysml(runId, nl, req.sysml, concept, idx, state, runDir, logPath),
      );
      await Promise.all(promises);
      state.status = "done";
      broadcast(runId);
    } catch (err) {
      state.status = "error";
      recordLog(state, logPath, (err as Error).message);
      broadcast(runId);
    }
  })();

  return { runId, state };
};
